name: Build SunamoGetFiles

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    name: Build SunamoGetFiles
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore SunamoGetFiles/SunamoGetFiles.csproj

    - name: Build
      run: dotnet build SunamoGetFiles/SunamoGetFiles.csproj --configuration Release --no-restore

  test:
    name: Test SunamoGetFiles.Tests
    runs-on: ${{ matrix.os }}
    needs: build

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore SunamoGetFiles.Tests/SunamoGetFiles.Tests.csproj

    - name: Build tests
      run: dotnet build SunamoGetFiles.Tests/SunamoGetFiles.Tests.csproj --configuration Release --no-restore

    - name: Run tests
      run: dotnet test SunamoGetFiles.Tests/SunamoGetFiles.Tests.csproj --configuration Release --no-build --verbosity normal
      continue-on-error: true
